project_id = "gbkpdgchdkkydpzycfkr"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.get-order]
verify_jwt = false

[functions.log-security-event]
verify_jwt = false
