// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbkpdgchdkkydpzycfkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdia3BkZ2NoZGtreWRwenljZmtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjQ0MzMsImV4cCI6MjA3MzEwMDQzM30.Ka-PdiOc-2PJqOW8RwVuGwHErX3tZ0XPs-W2MLVxLHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});